In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
kart = pd.read_excel('2017-2021 korea art auction.xlsx')
kart

       Artist     Bidding                     Title Company        Date
0         김환기  6550000000  고요(Silence) 5-IV-73 #310    케이옥션  2017.04.12
1         김환기  3895920000              Morning Star    서울옥션  2017.11.26
2     쿠사마 야요이  3339360000         A-PUMPKIN (BAGNB)    서울옥션  2017.11.26
3    무라카미 다카시  3200220000                     Panda    서울옥션  2017.11.26
4         김환기  2167650000             18-II-72 #221    서울옥션  2017.03.24
..        ...         ...                       ...     ...         ...
410       박서보   600000000              묘법 No.910614    서울옥션  2021.12.01
411        미상   500000000               요지연도 (瑤池宴圖)    서울옥션  2021.12.01
412       박서보   500000000              묘법 No.051128    서울옥션  2021.12.01
413   쿠사마 야요이   490000000                   Pumpkin    서울옥션  2021.12.01
414  무라카미 타카시   450000000   An Homage to Yves Klein    케이옥션  2021.12.01

[415 rows x 5 columns]

In [ ]:
sum(kart['Bidding']) / len(kart)

872947127.7108433

In [ ]:
sum(kart['Bidding']) / 415

872947127.7108433

In [ ]:
kart.groupby('Artist').agg(count_Artist = ('Artist', 'count')).sort_values('count_Artist', ascending = False)

           count_Artist
Artist
이우환                  75
김환기                  62
쿠사마 야요이              41
미상                   28
박서보                  28
...                 ...
안창홍                   1
알렉산더 칼더               1
게오르그 바젤리츠             1
앤디워홀                  1
황염수                   1

[83 rows x 1 columns]

In [ ]:
#2017-2021 한국 경매 낙찰 작품 수에 따른 작가 순위(작가 미상 제외 상위 10명)
kart.groupby('Artist').agg(count_Artist = ('Artist', 'count'))\
    .sort_values('count_Artist', ascending = False).head(11)

         count_Artist
Artist
이우환                75
김환기                62
쿠사마 야요이            41
미상                 28
박서보                28
박수근                17
정상화                16
김창열                13
마르크 샤갈              8
천경자                 8
이중섭                 7

In [ ]:
#2017-2021 한국 경매 낙찰 금액 순위(상위 30 작품)
kart2 = kart.query('Artist in ["이우환","김환기","쿠사마 야요이","박서보","박수근","정상화","김창열","마르크 샤갈","천경자","이중섭"]')\
            .sort_values('Bidding', ascending = False).head(30)

      Artist     Bidding                         Title Company        Date
31       김환기  8527480000                  3-II-72 #220    서울옥션  2018.05.27
100      김환기  7189600000                      Untitled    서울옥션  2019.05.01
0        김환기  6550000000      고요(Silence) 5-IV-73 #310    케이옥션  2017.04.12
395  쿠사마 야요이  5450000000                       Pumpkin    서울옥션  2021.11.01
34       이중섭  4700000000                             소    서울옥션  2018.03.07
336   마르크 샤갈  4200000000     Les Jardins de Saint Paul    케이옥션  2021.05.01
365      김환기  4000000000                 1-VII-71 #207    서울옥션  2021.08.01
35       김환기  3939070000                Jar and Poetry    서울옥션  2018.03.29
1        김환기  3895920000                  Morning Star    서울옥션  2017.11.26
150   마르크 샤갈  3764000000              Paysage de Paris    서울옥션  2019.11.01
385  쿠사마 야요이  3650000000                 Gold Sky Nets    서울옥션  2021.10.01
2    쿠사마 야요이  3339360000             A-PUMPKIN (BAGNB)    서울옥션  2017.11.26
36       김환기  3266000000                 27-XI-71 #211    서울옥션  2018.10.01
366      이우환  3100000000                    East Winds    서울옥션  2021.08.01
356  쿠사마 야요이  3100000000          Infinity-Nets (WFTO)    서울옥션  2021.07.01
346      김환기  3050000000                 27-XI-71 #211    서울옥션  2021.06.01
38       김환기  3000000000                  22-X-73 #325    케이옥션  2018.05.30
37       김환기  3000000000       Les Chants Éternels (B)    서울옥션  2018.03.07
347  쿠사마 야요이  2900000000           Silver Nets (BTRUX)    서울옥션  2021.06.01
232  쿠사마 야요이  2797020000          Soul Burning Flashes    서울옥션  2020.07.01
367  쿠사마 야요이  2550000000          Infinity-Nets (KPEU)    서울옥션  2021.08.01
405      이우환  2350000000                     From Line    서울옥션  2021.12.01
348   마르크 샤갈  2300000000  Le couple au-dessus de Paris    서울옥션  2021.06.01
314  쿠사마 야요이  2300000000          Infinity Nets (GKSG)    서울옥션  2021.03.01
40       김환기  2300000000                      달과 매화와 새    케이옥션  2018.05.23
140      박수근  2284650000         Children Playing Game    서울옥션  2019.10.01
406  쿠사마 야요이  2250000000            Infinity-Dots (AB)    케이옥션  2021.12.01
350      이우환  2200000000          From Point (2 works)    서울옥션  2021.06.01
349  쿠사마 야요이  2200000000         Infinity-Nets (OWTTY)    서울옥션  2021.06.01
41       김환기  2200000000             Montagne Mountain    서울옥션  2018.09.12

In [ ]:
kart2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 31 to 41
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Artist   30 non-null     object
 1   Bidding  30 non-null     int64
 2   Title    30 non-null     object
 3   Company  30 non-null     object
 4   Date     30 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.5+ KB

In [ ]:
#2017-2021 한국 경매 낙찰 금액 순위 작가(상위 30 작품의 작가)
kart2.groupby('Artist').agg(count_Artist = ('Artist', 'count'))\
     .sort_values('count_Artist', ascending = False)

         count_Artist
Artist
김환기                12
쿠사마 야요이            10
마르크 샤갈              3
이우환                 3
박수근                 1
이중섭                 1